import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel('data.xlsx')
print(df.info())
print(df.describe())
print(df.isnull().sum())
print(df['Customer ID'].duplicated())
#colors for matplotlib
color1 = ['#AB0012','#1C1919']
color2 = ['#FEC700','#02462E']
c12 = [color1 + color2]
#DATA cleaning
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])
df['Item'] = df['Item'].fillna('unknown')
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Price Per Unit'].median())
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())
df['Total Spent'] = df['Total Spent'].fillna(df['Total Spent'].median())
df.drop_duplicates(subset='Transaction ID',inplace=True)
df['Discount Applied'] = df['Discount Applied'].fillna('FALSE')
df['Category'] = df['Category'].str.lower()

# finding unique
unique_cust = df['Customer ID'].nunique()
print(unique_cust)
unique_items = df['Item'].nunique()
print(unique_items)
unique_category = df['Category'].nunique()
print(unique_category)
top_customers = df.groupby('Customer ID')['Total Spent'].sum().sort_values(ascending=False).head(5)
print("Top 5 Customers by Total Spend:\n", top_customers)

df['Month'] = df['Transaction Date'].dt.to_period('M')
monthly_sales = df.groupby('Month')['Total Spent'].sum()
plt.figure(figsize=(10,10))
monthly_sales.plot(kind='line',marker='o')
plt.title('Sales Distribution into months')
plt.xlabel('Months')
plt.ylabel('Profit')
plt.grid(color='Grey',linestyle="--",linewidth='0.5')
plt.savefig('Monthlyt Sales Distribution.png')
plt.show()
total_profit = df['Total Spent'].sum()
top5 = df.groupby('Item')['Quantity'].sum()
top5 = top5.sort_values(ascending=False).head(5)
print(f'Top % Items are \n {top5}')
plt.figure(figsize=(5,5))
plt.bar(top5.index,top5.values, color=color1)
plt.title('Top 5 Items Based on Quantity')
plt.xlabel('Items')
plt.ylabel('Quantity')
plt.grid(linestyle="--",linewidth="0.5")
plt.savefig('Top 5 Items.png')
plt.show()
top5categories = df.groupby('Category')['Total Spent'].sum().sort_values(ascending=False).head(5)
print(top5categories)
plt.figure(figsize=(5,5))
plt.barh(top5categories.index,top5categories.values,color=['#FEC700','#02462E','#AB0012','#1C1919'])
plt.title('Top 5 Categories Based on Total Spend')
plt.xlabel('Profit Made')
plt.ylabel('Categories')
plt.ylim()
plt.xlim(150000,230000)
plt.grid(color='grey',linestyle="--",linewidth="0.5")
plt.savefig('Top 5 Categories.png')
plt.show()
payment_methods = df['Payment Method'].value_counts()
print(payment_methods)
plt.figure(figsize=(5,5))
plt.pie(payment_methods, autopct='%1.1f%%', colors=['#AB0012','#1C1919','#FEC700','#02462E'], labels=['Cash','Digital Wallet','Credit Card'])
plt.title('Payment Methods')
plt.legend()
plt.savefig('Payment Methods.png')
plt.show()
df.to_excel("cleaned_data.xlsx", index=False)
